package salvacao.petcontrol.config;

import java.sql.*;

public class SingletonDB
{
    private static SingletonDB instancia;
    private Connection conexao;

    private SingletonDB()
    {
        try
        {
            Class.forName("org.postgresql.Driver");
            // Nome do banco de dados ALTERADO AQUI
            this.conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/petcontrol-db", "postgres", "postgres123");
        }
        catch(Exception e)
        {
            System.err.println("Erro ao conectar ao banco de dados (SingletonDB): " + e.getMessage());
            e.printStackTrace();
        }
    }

    public static synchronized SingletonDB getConexao() // Adicionado synchronized para thread-safety na criação da instância
    {
        if (instancia == null) {
            instancia = new SingletonDB();
        }
        return instancia;
    }

    public Connection getConnection()
    {
        // Adicionar verificação para tentar reconectar se a conexão estiver fechada ou nula
        try {
            if (this.conexao == null || this.conexao.isClosed()) {
                System.out.println("SingletonDB: Conexão nula ou fechada. Tentando reconectar...");
                // Recria a conexão
                Class.forName("org.postgresql.Driver");
                this.conexao = DriverManager.getConnection("jdbc:postgresql://localhost:5432/petcontrol-db", "postgres", "StrongP0stgres!");
                System.out.println("SingletonDB: Reconectado com sucesso.");
            }
        } catch (Exception e) {
            System.err.println("Erro ao tentar reconectar (SingletonDB): " + e.getMessage());
            e.printStackTrace();
            // Retorna null ou lança uma exceção se a reconexão falhar
            return null;
        }
        return this.conexao;
    }

    // Os métodos getPreparedStatement e manipular/consultar usariam this.getConnection()
    // Exemplo:
    public PreparedStatement getPreparedStatement(String sql) throws SQLException
    {
        Connection conn = getConnection();
        if (conn == null) throw new SQLException("Falha ao obter conexão com o banco de dados.");
        return conn.prepareStatement(sql);
    }

    public PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) throws SQLException
    {
        Connection conn = getConnection();
        if (conn == null) throw new SQLException("Falha ao obter conexão com o banco de dados.");
        return conn.prepareStatement(sql, autoGeneratedKeys);
    }

    public boolean manipular(String sql)
    {
        try(Connection conn = getConnection(); // Obtém e fecha a conexão para esta operação
            Statement stmt = conn.createStatement())
        {
            if (conn == null) return false;
            return stmt.executeUpdate(sql) > 0;
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            return false;
        }
    }

    public ResultSet consultar(String sql)
    {
        try
        {
            // Para consultas, a conexão precisa permanecer aberta até que o ResultSet seja processado.
            // Esta é uma limitação do design atual do SingletonDB se ele gerencia uma única conexão global
            // que é fechada por outros métodos como manipular().
            // Se o DAO fechar a conexão obtida de getConnection(), o ResultSet se torna inválido.
            // Idealmente, cada operação DAO obteria uma conexão e a fecharia.
            // A classe Conexao.java já faz isso de forma melhor (retorna uma nova conexão que o DAO gerencia com try-with-resources).
            Connection conn = getConnection();
            if (conn == null) return null;
            Statement stmt = conn.createStatement(); // O DAO precisaria fechar este stmt e o rs.
            return stmt.executeQuery(sql);
        }
        catch(SQLException e)
        {
            e.printStackTrace();
            return null;
        }
    }
}